language: python
python: 3.6
sudo: required
env:
  global:
  - K8S_OPS_REPO_BRANCH=master
  - K8S_OPS_REPO_SLUG=OpenBudget/budgetkey-k8s
  - DOCKER_IMAGE=budgetkey/budgetkey-app-themes
  - DEPLOY_YAML_UPDATE_FILE=values.auto-updated.yaml
  - DEPLOY_VALUES_CHART_NAME=themes
  - DEPLOY_VALUES_IMAGE_PROP=themesImage
  - DEPLOY_COMMIT_MESSAGE="automatic update of app themes"
  - DEPLOY_GIT_EMAIL=budgetkey-deployer@null.voids
  - DEPLOY_GIT_USER=budgetkey-deployer
  - secure: hMPOolojVrT+vikrT5f3+6+tTu8zQecCfqHseF7i5sLxuvcCn73lTnwt/q2LgBJSUibEUZCIhPT+oQ7a3WiUt9vb2ZuYnuqYyTBbnE0kuzykWn+ihJmK8HWiJtJcY02a7hZDs4Nog7dMS4jFdelxmbHVghZ7YQw3Tsm/MnueB7d7Rjf8onG61stzWmYMDc9sy4l3dr+fj5UQKMyNSU5M6lqdF66jFrL+RK9xemlpOPyWxJQO8UQzeXvqNd6f22mES7iUwoeusDV0kBtTrvwGDlbb6gHASxlVRiDIUaqKPGsftcvVhd6leQC5/2kBOBWon2WTNCaZaWJRUdL7Q9pm0A4qIwaFjUGYIg37NJ0UdH+wayPUsHC/wdjqFSld/KDDpXWuZ6Jt9p/Wkw61DfWLmIGn1xnW5xnjdJ8ded05uQ/Q/DDfXISPPWnupx8ObKZs2Cs0Ts+Bq3oNFK30aHrjPqk6FGsEV0hzDhrtMsQ9Qz+RNk3dvv9R52/3PaxhgnNjCq/qU9ODKEadaT+8KKzcXNQnQphoVIgC2rL8zGPRwDXR+5wThcUf3L74CzdN/lZLnShQ5Bs04yH0XJ911pTr30riTza8A+Amezf4jA+7LoKqWnu5oqAlnJBgJSp0L4+EZUAicP5ha9a1qZ0gQtgP9jSRCqXuwfkGb7DYrj7jBRo=
  - secure: svF+tZ5OGaRKsTm/vnBl17qfGrljSaMSg3Ract3rS8Y8WHdp8o103iFot1cWMcPnBWzdbUCzvBAmxurjwXVnntrdOMv6KkWmbY1jtEXtaIQl00JsD8Ympk3stXR8eMGSPh5czW4gh3ZR6wgrgWhzWsNFJoAj+qzO+u6cuAscdZqcY3pSHpspCynh3GI1lC2IcFhYs5xmi0z3khsnvaZeOCCPNnea6gsY2dXWAHFo6lFjQCfsJ1RL8N1NMdOod85TDWShvtv8tpc5QXCfXBXM2FwaAPtvnAPRFZqqfSbfLMngPHUPA7mZSL4S/lPR/AOewNZxmV1hsAMys7uVwuFtjxXJDknVAAt3kNkUqTW7YnCr1MnqQDlyeH3kpBY/q0M/46x3KSd6xJy2GjmXaLWiJffxnyB5lI2o/0qhliJjYIUw/QOeX4yPrPXZOKIIa5KmYEzmaMWUs3k0LHpWsKm4Ks1kstLzQNOgzK0Db1UJbgvMcG3cAq02KpQyxxVfroPrTJBOqlf1RDd5yMsTZNKmv3NvPUa272LKNKtZ58R+35jO8gZvZ3yJ8STmC2l7SMo/gQVhKwHPxf5lw1Vh2iwDNGR24tym/iUrikdPt05xe35qk6lgRCZxXKAx6gcJn4tJJ5tkawaEB7rLhYvKxnMVo5Au5ZEQW+KW2HVz1DZQ3vk=
  - secure: SPMFz0vfzq7rjnOvOtRcqiGoyCxBy3oHiWm3mVHfCFNSoyuuvxoHUudGXpkUhAvi+whNcCHebc9PWJaVaNqQ+ro/Y+eiPRz6j8Wwer/8yGrfcEuifPundLKf337bWE7rxmej4Z+6C1lz7P/yO/kCEnW7Wx08YclCQHznWsJ2+h1wtg7GsCnlKPyVFXEhz7qaVGLmKjrpNn8rCafM9fjTicZR/sZJz2zFXu269WIU8E8jBgz74KsQ6bzxz+NojC3sJHuK3KKo2L0qWLFCgXILb6GVx8w6t2DJmU+CJxoOGyB5yIq+BufHJ/50bzBe2orC7w9FSsDn6S2jej+IXfgjDmpjGWZPfY7dT/jC0f6rxNJW9dgdPRgmbGhU9CzCMTUMTUqHe9ojq9fa3lcvvsjf5d7z+onj8/Tpq0XjVL9FBJiETSoeq8Z+f5nOSHmivYPletNp7CsU3hr7qPfe+9PyLlPZdgzcNnwt1dRN6LRhIFDsxgLG8lTi7rSH2aipREvSMMlTIPJwG8OVw1eO+XTo6VnEDolUKauaPdCLCcteBte/aThAywh830r/Uhpo3CIVWZdjsLewq4Q4ok9Se3sCGtt04+lvLqmW9lABfe/aiIzTaap74zXT2WKQnBhRGuFeF1sqDhazKJmG902Hgd1c8W99nmJUzi6F+wCOK5vAoqs=
  - secure: sgRhbW5sO8wFTJ6kXHCPp/CrfG5IMQZoEUtj2pbcYNet9HM41yvOzgJ+Ka0jB7kI/PBNUXGnAPjPTAeNHcgwazanajviepptZICbhQA4A7NqwenMZe0cynRhSlhntdBz1zkh++425HSoVBgKHWubhFhezfBRiIUAUz6HVIMfrasOkWohhnKN3fChsIqCwnFuTTU6nka4UnjNpFK15f6rTYV7W5LgQY/Zhz/B3I/1MOmLxdATTHoZCP63vqjb3RpHN4ipucl8IuACi24aE54I3qjjZI78MdPn79b99b7wsWnjZ6+isOjcjQxnVfNf2nfaTuXZXttn5pjsdmsH+53oqKxlPCT7HfSBFA+Y+J6uRa55zEgBBUKe74Tiqs1roMLmcyusXpDhkXzIHl6SOXIZud/rhZ6X5JrTpnF+HWAviXAr24HYyZ3wfaKJZjsSBAEz+Ckd1B6PwVzJfJYBgQ/ezzz9gZNiKLpDQUfn8XK3fyUkf1R9yPHFsdSEYjCdexY+uJb8P6sV1+sN+uSNXDY84IQvTYLEQ1eMixvYXqbIlfd5KD4Q/XMkM39Lh/lGQJrszes9MQFQjQtpeDnVmGXtrDfw0CQF3HiCqSu+/8M+lPoozQhsMkPK2e3w8AiDPHubWyWx7DHju6H5rTLfvEIaQB4KsBsJUy5TvHk1UQ4zm6k=
services:
- docker
install:
- pip install PyYAML
script:
- python extract_translations.py
- curl -s https://raw.githubusercontent.com/OpenBudget/budgetkey-k8s/master/apps_travis_script.sh
  > .travis.sh
- bash .travis.sh script
deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis.sh deploy
  on:
    branch: master
